version: '3.8'

services:
  app:
    build: .
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"